services:
  sveltekit:
    build:
      context: ./frontend-svelte
    ports:
      - "3005:3000"
    networks:
      - washed-up-ez-network
    depends_on:
      - laravel
    environment:
      ORIGIN: ${ORIGIN}
      API_URL: http://laravel
      AUTH_SECRET: ${AUTH_SECRET}

  laravel:
    build:
      context: ./backend-laravel
    ports:
      - "99:80"
    networks:
      - washed-up-ez-network

networks:
  washed-up-ez-network:
    driver: bridge