services:
  new-sveltekit:
    build:
      context: ./frontend-svelte
    ports:
      - "3000:3000"
    networks:
      - washed-up-ez-network
    depends_on:
      - new-laravel
    environment:
      ORIGIN: ${ORIGIN}
      API_URL: http://new-laravel
      AUTH_SECRET: ${AUTH_SECRET}

  new-laravel:
    build:
      context: ./backend-laravel
    ports:
      - "99:80"
    networks:
      - washed-up-ez-network

networks:
  washed-up-ez-network:
    driver: bridge