services:
  test_sveltekit:
    build:
      context: ./frontend-svelte
    ports:
      - "3005:3000"
    networks:
      - washed-up-ez-network
    depends_on:
      - test_laravel
    environment:
      ORIGIN: ${ORIGIN}
      API_URL: http://test_laravel
      AUTH_SECRET: ${AUTH_SECRET}

  test_laravel:
    build:
      context: ./backend-laravel
    ports:
      - "80:80"
    networks:
      - washed-up-ez-network

networks:
  washed-up-ez-network:
    driver: bridge